using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MyFirstProject
{
  class InteropCommand
  {
     //AcadApplication acAppComObj = null;
      //const string strProgID = "Autocade.Application.20";

      //try
      //{
      //  acAppComObj = (AcadApplication)Marshal.GetActiveObject(strProgID);
      //}
      //catch
      //{
      //  try
      //  {
      //    acAppComObj = (AcadApplication)Activator.CreateInstance(Type.GetTypeFromProgID(strProgID), true);
      //  }
      //  catch
      //  {
      //    System.Windows.Forms.MessageBox.Show("no autocad loaded");
      //    return;
      //  }
      //}


      //acAppComObj.Visible = true;
      //System.Windows.Forms.MessageBox.Show("acad loaded");

      //AcadDocument acDocComObj;
      //acDocComObj = acAppComObj.ActiveDocument;

      //acDocComObj.SendCommand("._trim")
  }
}
